config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

# roomsコントローラーのonlyオプションにdestroyアクションが追加された理由とは？
# 今回をルーム削除機能を実装したいためそのコントローラーにそのアクションを追加している

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?
# validatesのunlessオプションにメソッド名を指定することでメソッドの返り値がfalseであればバリデーションの検証を行う つまり 投稿をするときに画像が空であればcontentが空であるかどうかを検証する
# was_attached?メソッドはrailsにあるメソッドではなく自分が作り出したメソッドなのでdef~endを用いてメソッドの処理を記述している
  
  def was_attached?
    self.image.attached?
# 投稿をするときに画像があればtrueを 無ければfalseを返す
# つまり unlessは結果がfalseであれば処理がされるので trueであった場合はcontentが空であるかの検証はされない
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users  
  has_many :messages, dependent: :destroy
# チャットルームが削除された時に一緒に削除されて欲しいものはroom_idが保存されているroom_usersテーブルとmessagesテーブルなのでそれらにdependent: :destroyをつけている

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
  # RoomUsersテーブルとroom userテーブルの関係は１対多の関係であるためbelongs_toオプションを使っている
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  # ユーザーは複数のメッセージを送信できるのでhas_manyを使っている
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # ApplicationControllerにこれを記述している理由はこのコントローラーは他の全てのコントローラを司っていて他のコントローラーに before_action :authenticate_user! を読み込ませている
# だから他のコントローラーに before_action :authenticate_user! を書く必要がない
# before_actionを用いることで各アクションが動く前にそれに続けて記述したメソッドが実行される
# authenticate_user!メソッドはユーザーがログインしていなければログイン画面に遷移させる
  before_action :configure_permitted_parameters, if: :devise_controller?
  # configure_permitted_parametersというメソッド名は慣習的なものなので自分で自由に決めて良い
 # ifに続いてメソッド名(?がついているので真偽値を確かめることができる)を指定することでそのメソッドの返り値がtrueであった時のみconfigure_permitted_parametersメソッドが実行される
 # devise_controller?メソッドはdeviseのコントローラーの処理であればtrueを返す

  private
  def configure_permitted_parameters # このメソッド名は自由に決めることができる
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # devise特有のパラメータを取得するためにdevise_parameter_sanitizerという記述をしている
  # これを記述することでdeviseのUserモデルに関する「ログイン」「新規登録」などをしたときにパラメーターを取得することができる
  # このメソッドにpermitメソッドを使うことで取得したいキーを指定することができ指定したキーとそのバリューを取得することが出来る
  # sign_up(新規登録)はdeviseの処理名を表していて、今回は新規登録をする際のストロングパラメータに関するものなので第一引数には:sign_upと記述している
  # 第二引数にはkeysに対し配列で許可するキーを指定している
  # deviseのストロングパラメータはそれのコントローラーがgemに記述されているため編集ができないのでこのコントローラーに記述している
  # Railsでのpermitメソッドとの記述が違う理由はこのpermitmメソッドはdeviseで定義されたものだから
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  # アソシエーションを利用しているのでDBへのアクセス回数が多くなる
  # 今回はmessagesテーブルに関するusersテーブルの情報の取得をするためにメッセージと同じ回数アクセスが必要になる(これをN+1問題と呼ぶ)
  # その問題を解決するためにincludesメソッド(これはallメソッドの代わりにもなっている！)を使っている
  # @room.messagesはどのチャットルームで投稿されたメッセージなのかを意味している
  # それにincludesメソッドを使用してさらに引数にmessagesテーブルに紐づくモデル名(今回はuser)を用意することでDBへのアクセス回数が減りN+1問題を解決できる
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
    # このように記述することで保存に失敗した場合でも投稿前と同じメッセージ一覧になっている
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  # フォームから送られてきたparamsのハッシュからrequireメソッドを使いmessageキーのバリューを取り出している
  # そのバリューの中にあるキーであるcontentキー, imageキーの値をpermitメソッドを使いmessagesテーブルに保存を許可している
  # 誰がメッセージを投稿したかを判別するためにmergeメソッドを使いuser_id(誰が)の部分をcurrent_user.id(現在ログインしているユーザー)にしている
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    # ルートパスが送られた次にコントローラにroomsのindexは無いかを確認するのでこの記述は必要
    # この記述があることでroomsのindex.html.erbを表示できる
  end
  
  def new
    @room = Room.new
  # 新規チャットルームを作成するためにroomsテーブルにnewメソッドを使うことで新規のインスタンスを作成している
  end

  def create
    @room = Room.new(room_params)
  # Roomモデルの新規のインスタンスを作成している
  # フォームから送られたparamsの値を受け取るために引数を用意している(引数名は任意で決められる)
  # なぜ引数を用意しているのかというとフォームから入力された値が正しいものかを確かめるためである
    if @room.save
      redirect_to root_path
  # 保存に成功した場合はチャット画面に遷移する
    else
      render :new
  # 保存に失敗した場合はroomsのnew.html.erbに遷移する
  # renderメソッドを使用しているので入力したものは消えずに残っている
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end
  # destroyアクションの処理の流れについて
  # ①ルームを削除しようとしたときrooms#destroyのURIは/rooms/:idなのでビューからparamsを通してハッシュでルームのidが送られてくる そのキーからバリューを取り出すためにparams[:id]と記述するそれがfindメソッドの引数となりroomsテーブルのレコードを取得できる
  # ②destroyメソッドを使うことでroomという変数に代入したレコードを削除できる
  # ③roomsコントローラーのindexアクションのビューに遷移する(チャット内容が表示されていない画面に遷移する)

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  # requireメソッドを使ってroomモデルというパラメーターから情報を取得している
  # permitメソッドを使用することで指定したキーの値を保存することができる
  # user_idsに関してはフォームから配列でコントローラーに送られてくるため[]を用意している
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
# このコントローラーにeditアクションを書き忘れるとエラーが起きる その理由は・・・
# 編集画面に遷移するために/users/:id/editというパスが送られルーティングでusersコントローラーのeditアクションを探しにいく そこでeditアクションを見つけたら今度はusersコントローラーにeditアクションがあるかどうか探しにいく
# ここで仮にusersコントローラーのeditのビューファイルがあったとしてもusersコントローラーにeditアクションがありませんということでエラーが表示される

def update
  if current_user.update(user_params)
    redirect_to root_path
  # 現在ログインしているユーザーの情報の更新に成功した場合トップページに遷移する
  # root_pathについてですがこれはrails routesで確認するとmessages#indexのPrefixのrootを参照している
  else
    render :edit
  # 現在ログインしているユーザーの情報の更新に失敗したとき編集画面に遷移する
  # renderメソッドを使用しているので入力した情報は残ったままである
  end
end

private

def user_params
  params.require(:user).permit(:name, :email)
# 送られたparamsの情報にはusersテーブルが2重ハッシュになっているので取り出すためにrequireメソッドを使用している
# 送られたparamsの情報にあるnameカラムとemailカラムの保存を許可している
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
<%# 右側の要素で一番上の要素である %>
  <div class="left-header">
<%# chat-headerの子要素を横並べにさせるためにこのようなdivを作っている %>
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
<%# link_toメソッドにより チャットを終了する と表示されそれがリンクとなる %>
<%# roomsコントローラーのdestroyアクションのパスを指定したいのでroom_pathを指定している %>
<%# そのパスのURIには/rooms/:idとあるので削除するルームのidを送らなければならないので引数にはroomsコントローラーのcreateアクションの@room = Room.new(room_params)の@roomをセットしている %>
<%# 今回verbがDELETEなのでmethod: :deleteを追加している %>
    </div>
  </div>
</div>


<div class="messages">
  <%= render partial: 'message', collection: @messages %>
<%# @messagesのレコードの数だけ_messages.html.erbを表示させる %>
</div>


<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
<%# form_withのmodelオプションで@room, @messageというインスタンス変数を指定している理由は %>
<%# messagesコントローラーがroomsコントローラーにネストされているからである %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
<%# placeholder属性に文字列を入れるとブラウザではうっすら表示される %>
    <label class="form-image">
<%# labelタグを使うことで子要素が非表示でもクリックすることができる %>
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
<%# file_fieldを使うことで画像をアップロードすることができる %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<%# submitを使うことで送信ボタンを作成することができる %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
  <%# collectionオプションで@messagesを指定したためrender partialで読み込まれるビューファイルではmessagesテーブルのレコードが入った変数messageを使うことができる %>
  <%# messagesテーブルとusersテーブルにはアソシエーションが組まれているのでこのような記述ができる %>
  <%# messagesテーブルのuser_idカラムを参照してそこからusersテーブルのnameカラムが表示できる %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
  <%# messagesテーブルのレコードが作成された時間を表している %>
  <%# 似たようのものでupdated_atカラムが存在するがそれはレコードが更新された時間を表しているので混同しないように注意する %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
<%# messagesテーブルのレコードにファイルが添付されているかどうかをattached?メソッドで検証している %>
<%# 画像が紐づいたモデル名.画像のファイル名.attached?とすることでメッセージを投稿したときに画像が添付されていないときは画像が表示されなくなる %>
<%# メッセージを投稿したときに画像が添付されているときは image_tagからclass: 'message-image'まで読み込まれる %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
<%# 親要素のside-bar-headerの子要素としてheader-nameというdivを作っている %>
     <%= link_to current_user.name, edit_user_path(current_user) %>
<%# 「チャットを作成する」ボタンの隣に現在ログインしているユーザーの名前がリンクとして表示される %>
<%# そのリンク先を編集ページにしたいのでrails routesで確認するとusers#editにあたるprefixがedit_user なのでそのようなpath名にしている %>
<%# なぜそのパスに引数としてcurrent_userが渡されているのかというと理由は２つあります %>
<%# ①パスが送られた(クリックした)ときに編集画面の入力欄にcurrent_userの情報を残しておきたいから %>
<%# ②URI patternとして/users/:id/editとあり編集をするにはcurrent_userの情報を持たせないといけないから %>
<%# ②に関してだがidの情報を持たせれば良いので引数名をcurrent_user.idにしてもエラーは起こらない %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>


<div class="rooms">
   <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
<%# 現在ログインしているユーザーが属しているルーム名が表示されそれがメッセージ一覧を表示するリンクとなる %>
<%# メッセージ一覧を表示するパスはrails routesで確認するとroom_messagesとなっているのでそのパス名を記述する %>
<%# messagesコントローラーはroomsコントローラーにネストされたためroom_messages_pathのURIが/room/:room_id/messagesとなっているのでroomsテーブルのレコードのidを引数としてpathと共にコントローラーに送らなければならない %>
<%# 引数名がroomになっている理由は現在ログインしているユーザーが属しているroomsテーブルのレコードが変数roomに格納されているので引数名がそのようになっている %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
<%# ブラウザ全体を指している %>
  <div class="side-bar">
  <%# 左側の要素を表している %>
    <%= render "side_bar" %>
  <%# _side_bar.html.erbを読み込んでいる %>
  </div>
  <div class="chat">
  <%# 右側の要素を表している %>
    <%= render "main_chat" %>
    <%# _main_chat_.html.erbを読み込んでいる %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
<%# renderメソッドを使用することで外部のビューファイルを読み込んでいる %>
<%# messagesフォルダの_side_bar.html.erbを読み込んでいる %>
  </div>
</div>

<%# チャットルーム一覧を表示させるビューを作成したかったのでroomsのindex.html.erbを作った %>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
  <%# form_withの引数として@roomを渡している %>
  <%# この@roomはRoomsControllerのRoom.new(roomsテーブルの新規のインスタンス)を指していて %>
  <%# このようにすることで@roomが適切なパスに送られチャットルームを作成することができる %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
        <%# roomは@roomからきているものである %>
        <%# select要素のname属性にroom[user_ids][]と記述することで選択したユーザーのidをparamsを通してコントローラーに送ることができる %>
        <%# room[user_ids]が何を指しているのかいうとuser_idsのバリューを取得するためのもの %>
        <%# [] は取得したバリューが複数あった時に配列として受け取れるようにしている%>
          <option value="">チャットするユーザーを選択してください</option>
        <%# value属性に空の値を入れることでこれを選択してもコントローラーには何も送られない %>
          <% User.where.not(id: current_user.id).each do |user| %>
        <%# usersテーブルから現在ログインしているユーザーのidを取り除いたものを取得していてそのレコードの数だけdo~endが繰り返される %>
        <%# そのレコード1つ1つが変数userに格納されていく %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
        <%# name属性にroom[user_ids][]と指定することでuser_idsのバリューを取得できる %>
        <%# []があることでバリューが複数あった時はそれらを配列に入れてコントローラに送れるようにしている %>
        <%# value属性にcurrent_user.idを指定することで現在はプルダウンで非表示になっている人のidもコントローラー側に送ることができる %>
        <%# input要素のtype属性に"hidden"を指定することでこのフォームはブラウザでは非表示になる %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
<%# link_toメソッドを使用することで ログアウト と表示されそれがリンクとなる  %>
<%# rails routesで確認するとdevise/sessions#destroyのpathがdestroy_user_sessionというprifixになっているのでそのパス名を記述している %>
<%# method: :deleteを指定している理由が何も記述しないとデフォルトでmethod:getがかかっているためVerbがgetである間違ったパスを読み込んでしまいそれによって間違ったコントローラーのアクションが作動してしまうことを防ぐためである %>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>